spring:
  main:
    allow-circular-references: true
    web-application-type: none
  cache:
    cache-names: apiCache
    caffeine:
      spec: expireAfterAccess=5m, maximumSize=100000

starbot:
  bilibili:
    log:
      console: INFO
      file: INFO
    version:
      number: 3.0.0
      release-date: 2025-03-09