server:
  port: 7827

spring:
  main:
    allow-circular-references: true
  cache:
    cache-names: apiCache
    caffeine:
      spec: expireAfterAccess=5m, maximumSize=100000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

starbot:
  bilibili:
    log:
      console: INFO
      file: INFO